version: "3"

services:
  webserver1:
    image: ubuntu
    container_name: web-container

  webserver2:
    build:
      context: .
      labels:
        - "com.example.description=Accounting webapp"
        - "com.example.department=Finance"
        - "com.example.label-with-empty-value"
