# 버전을 지정
version: "3"

# 서비스 정의
services:
  webserver:
    image: ubuntu
    ports:
      - "80:80"
    networks:
      - webnet

  redis:
    image: redis
    networks:
      - webnet

# 네트워크 정의
networks:
  webnet:

# 데이터 볼륨 정의
volumes:
  data-volume:
